arm:
  # kinematics_solver: cobot_kinematics_plugin/CobotKinematicsPlugin
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin  
  
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.05
  position_only_ik: true
