controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    position_controller:
      type: position_controllers/JointGroupPositionController

    cobot_controller:
      type: cobot_controller/CobotController

position_controller:
  ros__parameters:
    joints:
      - part-1-joint
      - part-2-joint
      - part-3-joint
      - part-4-joint
      - part-5-joint
      - part-6-joint
      - finger-1-joint
      - finger-2-joint
  
cobot_controller:
  ros__parameters:
    part_1_joint: "part-1-joint"
    part_2_joint: "part-2-joint"
    part_3_joint: "part-3-joint"
    part_4_joint: "part-4-joint"
    part_5_joint: "part-5-joint"
    part_6_joint: "part-6-joint"
    finger_1_joint: "finger-1-joint"
    finger_2_joint: "finger-2-joint"
    angle_degree: 0.1
